[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ViDL"
version = "1.0.0"
authors = [
    { name = "aredigg" },
]
description = "A pretty CLI frontend to yt-dlp"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "yt-dlp",
]

[project.scripts]
vidl = "vidl.__main__:main"

[tool.setuptools]
packages = ["vidl"]
